apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-nfs
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.25
    path: "/volume1/k8-cluster-storage/postgres"
