apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: get-velibs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: get-velibs
    spec:
      containers:
      - name: get-velib
        image: achntrl/velib:0.1.1
