apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: datadog-agent
  annotations:
    ad.datadoghq.com/datadog-agent.logs: '[{"service":"agent","source":"agent"}]'
spec:
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
    spec:
      serviceAccountName: datadog-agent
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - image: achntrl/datadog-agent:6.6.0-beta-2
        # imagePullPolicy: Always
        name: datadog-agent
        ports:
          - containerPort: 8125
            name: dogstatsdport
            protocol: UDP
          - containerPort: 8126
            name: traceport
            protocol: TCP
        env:
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog
                key: api_key
          - name: KUBERNETES
            value: "true"
          - name: DOCKER_DD_AGENT
            value: "true"
          # - name: DD_COLLECT_KUBERNETES_EVENTS
          #   value: "true"
          - name: DD_LEADER_ELECTION
            value: "true"
          - name: DD_LOGS_ENABLED
            value: "true"
          - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
            value: "true"
          # - name: DD_PROCESS_AGENT_ENABLED
          #   value: "true"
          # - name: DD_EXTERNAL_METRICS_PROVIDER_ENABLED
          #   value: 'true'
          - name: DD_KUBERNETES_KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
          - name: pointerdir
            mountPath: /opt/datadog-agent/run
          - name: docker
            mountPath: /var/lib/docker/containers
          - name: datadog-config-volume
            mountPath: /etc/datadog-agent/datadog.yaml
            subPath: datadog.yaml
          - name: datadog-config-volume
            mountPath: /etc/datadog-agent/conf.d/traefik.yaml
            subPath: traefik.yaml
          - name: datadog-config-volume
            mountPath: /etc/datadog-agent/conf.d/docker.yaml
            subPath: docker.yaml
          - name: datadog-config-volume
            mountPath: /etc/datadog-agent/conf.d/prometheus.d/conf.yaml
            subPath: prometheus.yaml
          - name: datadog-config-volume
            mountPath: /etc/datadog-agent/conf.d/kubernetes_apiserver.d/conf.yaml
            subPath: apiserver.yaml
          - name: datadog-config-volume
            mountPath: /etc/datadog-agent/conf.d/kubelet.d/conf.yaml
            subPath: kubelet.yaml
          - name: datadog-config-volume
            mountPath: /etc/datadog-agent/conf.d/disk.d/conf.yaml
            subPath: disk.yaml
          # - name: passwd
          #   mountPath: /etc/passwd
          #   readOnly: true
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - hostPath:
            path: /opt/datadog-agent/run
          name: pointerdir
        - hostPath:
            path: /var/lib/docker/containers
          name: docker
        - configMap:
            name: datadog-config
          name: datadog-config-volume
        # - hostPath:
        #     path: /etc/passwd
        #   name: passwd
