---
apiVersion: v1
kind: Service
metadata:
  name: datadog-service
spec:
  selector:
    app: datadog-agent
  ports:
  - port: 8125
    protocol: UDP
    targetPort: 8125
    nodePort: 30125
  type: NodePort
