apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-config
data:
  datadog.yaml: |
    listeners:
    - name: kubelet
    config_providers:
    - name: kubelet
      polling: true
    leader_election: true
  kubelet.yaml: |
    init_config:
    instances:
    - {}
  apiserver.yaml: |
    init_configs:
    instances:
    - {}
  docker.yaml: |
    init_config:
    instances:
    - {}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: datadog-agent
spec:
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - image: achntrl/dd-agent:6.5.1
        imagePullPolicy: Always
        name: datadog-agent
        ports:
          - containerPort: 8125
            name: dogstatsdport
            protocol: UDP
          - containerPort: 8126
            name: traceport
            protocol: TCP
        env:
          - name: DD_API_KEY
            value: <obfuscated>
          - name: KUBERNETES
            value: "true"
          - name: DOCKER_DD_AGENT
            value: "true"
          - name: DD_COLLECT_KUBERNETES_EVENTS
            value: "true"
          - name: DD_LEADER_ELECTION
            value: "true"
          - name: DD_LOGS_ENABLED
            value: "true"
          - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
            value: "true"
          - name: DD_KUBERNETES_KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
          - name: pointerdir
            mountPath: /opt/datadog-agent/run
          - name: docker
            mountPath: /var/lib/docker/containers
          - name: datadog-config-volume
            mountPath: /etc/datadog-agent/datadog.yaml
            subPath: datadog.yaml
          - name: datadog-config-volume
            mountPath: /etc/datadog-agent/conf.d/kubernetes_apiserver.d/conf.yaml
            subPath: apiserver.yaml
          - name: datadog-config-volume
            mountPath: /etc/datadog-agent/conf.d/kubelet.d/conf.yaml
            subPath: kubelet.yaml
        livenessProbe:
          exec:
            command:
            - /probe.sh
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - hostPath:
            path: /opt/datadog-agent/run
          name: pointerdir
        - hostPath:
            path: /var/lib/docker/containers
          name: docker
        - configMap:
            name: datadog-config
          name: datadog-config-volume
