apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-acme
  namespace: kube-system
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
      server: 192.168.0.25
      path: "/volume1/k8-cluster-storage/traefik"
