apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dns-update
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 20
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dns-update
            image: evns/rpi-utilities
            command: [ "/bin/sh", "-c", "source /etc/config/update.sh" ]
            env:
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: dns-update
                  key: email
            - name: RECORD_NAME
              valueFrom:
                secretKeyRef:
                  name: dns-update
                  key: record_name
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: dns-update
                  key: api_key
            - name: ZONE_ID
              valueFrom:
                secretKeyRef:
                  name: dns-update
                  key: zone_id
            volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          volumes:
          - name: config-volume
            configMap:
              name: update-script
          restartPolicy: OnFailure
