apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gogs-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: gogs.home.achntrl.com
    http:
      paths:
      - backend:
          serviceName: gogs-app
          servicePort: 3000
