apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
      server: 192.168.0.25
      path: "/volume1/k8-cluster-storage/gogs/db"
